'use client';
import { useCallback, useEffect, useState } from 'react';
import { Activity, AlertCircle, CheckCircle2, RefreshCw, TrendingDown, TrendingUp } from 'lucide-react';
import api from '@/services/api';
import { cn, formatCurrency } from '@/lib/utils';

export function PredictionMarketSetup({ symbol }: { symbol: string }) {
    const [data, setData] = useState<any>(null);
    const [error, setError] = useState<string | null>(null);
    const [loading, setLoading] = useState(true);
    const load = useCallback(async () => {
        setLoading(true); setError(null);
        try { setData((await api.get(`/market-data/${symbol}/prediction`)).data); }
        catch (err: any) { setError(err.response?.data?.error || 'Unable to calculate the current market setup.'); }
        finally { setLoading(false); }
    }, [symbol]);
    useEffect(() => { load(); }, [load]);
    if (loading) return <div className="bg-white dark:bg-slate-800 p-8 rounded-3xl border border-gray-100 dark:border-gray-700 animate-pulse"><div className="h-32 rounded-2xl bg-gray-100 dark:bg-slate-700" /></div>;
    if (error || !data) return <div className="bg-white dark:bg-slate-800 p-8 rounded-3xl border border-gray-100 dark:border-gray-700 text-center"><AlertCircle className="mx-auto text-amber-500 mb-2" /><h3 className="font-bold">Prediction & Market Setup Unavailable</h3><p className="text-xs text-gray-400 mt-1">{error}</p></div>;
    const { prediction, support, resistance, pattern, trend, momentum, volume, marketStructure, breakout, rationale, hypotheticalSetup } = data;
    const buy = prediction.recommendation === 'BUY', sell = prediction.recommendation === 'SELL';
    const badge = buy ? 'bg-emerald-500' : sell ? 'bg-red-500' : 'bg-amber-500';
    const Metric = ({ label, value }: { label: string, value: any }) => <div className="flex justify-between gap-4 text-sm"><span className="text-gray-500 dark:text-gray-400">{label}</span><span className="font-bold text-gray-900 dark:text-white text-right">{value ?? 'N/A'}</span></div>;
    return <div className="bg-white dark:bg-slate-800 p-6 md:p-8 rounded-3xl border border-gray-100 dark:border-gray-700 shadow-sm space-y-7">
        <div className="flex justify-between border-b border-gray-100 dark:border-gray-700 pb-4"><div><h2 className="text-xl font-black flex gap-2 items-center"><Activity className="text-violet-500" />PREDICTION & MARKET SETUP</h2><p className="text-xs text-gray-400 mt-1">Current rule-based setup, not a future price prediction</p></div><button onClick={load} className="p-2 text-gray-400 hover:text-violet-500"><RefreshCw size={17} /></button></div>
        <div className="rounded-3xl bg-gray-50 dark:bg-slate-700/30 p-6 flex flex-col md:flex-row justify-between gap-5"><div><div className={cn('inline-block px-4 py-2 rounded-xl text-white text-lg font-black', badge)}>{prediction.recommendation}</div><p className="font-bold mt-3">{prediction.bias.replace('_', ' ')} setup</p><p className="text-xs text-gray-500 mt-1">Setup strength measures agreement among configured rules.</p></div><div className="text-right"><p className="text-xs uppercase font-bold text-gray-400">Setup Strength</p><p className="text-4xl font-black">{prediction.setupStrength}<span className="text-lg text-gray-400"> / 100</span></p><p className="text-xs text-gray-500">{prediction.strength}</p></div></div>
        <div className="grid grid-cols-1 md:grid-cols-3 gap-4"><section className="rounded-2xl bg-gray-50 dark:bg-slate-700/30 p-5 space-y-3"><h3 className="font-black text-sm">PRICE STRUCTURE</h3><Metric label="Current price" value={formatCurrency(data.currentPrice)} /><Metric label="Support" value={support.nearest ? formatCurrency(support.nearest) : null} /><Metric label="Resistance" value={resistance.nearest ? formatCurrency(resistance.nearest) : null} /><Metric label="To support" value={support.distancePercent != null ? `${support.distancePercent}%` : null} /><Metric label="To resistance" value={resistance.distancePercent != null ? `${resistance.distancePercent}%` : null} /></section><section className="rounded-2xl bg-gray-50 dark:bg-slate-700/30 p-5 space-y-3"><h3 className="font-black text-sm">TREND & MOMENTUM</h3><Metric label="Trend" value={trend.direction.replace('_', ' ')} /><Metric label="RSI" value={momentum.rsi} /><Metric label="MACD" value={momentum.macdState} /><Metric label="Volume" value={`${volume.relativeVolume}x (${volume.state})`} /><Metric label="Structure" value={marketStructure.type.replaceAll('_', ' ')} /></section><section className="rounded-2xl bg-gray-50 dark:bg-slate-700/30 p-5 space-y-3"><h3 className="font-black text-sm">PATTERN & BREAKOUT</h3><Metric label="Pattern" value={pattern.name || 'None'} /><Metric label="Pattern bias" value={pattern.type || 'N/A'} /><Metric label="Breakout" value={breakout.detected ? breakout.type.replace('_', ' ') : breakout.status || 'None'} /><Metric label="ATR volatility" value={data.risk.atrPercent != null ? `${data.risk.atrPercent}%` : null} /></section></div>
        <div className="grid md:grid-cols-2 gap-4"><section className="rounded-2xl border border-emerald-100 dark:border-emerald-900/30 p-5"><h3 className="font-black text-sm flex gap-2 items-center"><CheckCircle2 size={16} className="text-emerald-500" />WHY THIS SIGNAL</h3>{rationale.positive.length ? rationale.positive.map((x: string, i: number) => <p key={i} className="text-sm mt-3 text-emerald-700 dark:text-emerald-300">✓ {x}</p>) : <p className="text-sm mt-3 text-gray-500">No strong bullish confirmations.</p>}</section><section className="rounded-2xl border border-amber-100 dark:border-amber-900/30 p-5"><h3 className="font-black text-sm flex gap-2 items-center"><AlertCircle size={16} className="text-amber-500" />WARNINGS</h3>{rationale.warnings.length ? rationale.warnings.map((x: string, i: number) => <p key={i} className="text-sm mt-3 text-amber-700 dark:text-amber-300">⚠ {x}</p>) : <p className="text-sm mt-3 text-gray-500">No material warnings from configured rules.</p>}</section></div>
        {hypotheticalSetup && <section className="rounded-2xl bg-violet-50 dark:bg-violet-900/10 border border-violet-100 dark:border-violet-900/30 p-5"><h3 className="font-black text-sm">HYPOTHETICAL SETUP</h3><div className="grid grid-cols-2 md:grid-cols-4 gap-4 mt-3"><Metric label="Entry" value={formatCurrency(hypotheticalSetup.entry)} /><Metric label="Stop" value={formatCurrency(hypotheticalSetup.stop)} /><Metric label="Target" value={formatCurrency(hypotheticalSetup.target)} /><Metric label="Risk / Reward" value={hypotheticalSetup.riskReward ?? 'N/A'} /></div></section>}
        <p className="text-xs leading-relaxed text-gray-400 border-t border-gray-100 dark:border-gray-700 pt-4">This recommendation is generated using predefined quantitative rules and historical/current market data. It is intended for educational and backtesting purposes, does not guarantee future price movements or returns, and is not financial advice.</p>
    </div>;
}
